### PR TITLE
Create a States class to ease state access

### PR DESCRIPTION
**Pull request by tetienne**
Allow this kind of syntax:

```python
        devices = await client.get_devices()

        for device in devices:
            if device.states:
                if "core:RSSILevelState" in device.states:
                    print(device.states["core:RSSILevelState"].name)
                    print(device.states["core:RSSILevelState"].value)

```

### CODE REVIEW

**Comment by tetienne** [comment]
@iMicknl Code update, you should like :)

**Comment by iMicknl** [comment]
> @iMicknl Code updated, you should like :)

LGTM! I see you marked it as a draft, so I will let you merge it yourself when you are ready :).

**Comment by tetienne** [comment]
Yes I saw a potential issue for the command in operator. I have to check.

**Comment by iMicknl** [comment]
@tetienne we should pin the version in the component and bump it here. Now an update to master can break the component.

Looks like it did now?

**Pull request merged**
