### PR TITLE
Default to empty list instead of None

### PR DESCRIPTION
**Pull request by tetienne**
We often iterate over states or attributes, to ease client code, I suggest to return an empty list instead of None when the data does not exist. It will avoid None check.

### CODE REVIEW

**Comment by iMicknl** [comment]
@tetienne do we need to list this as a breaking change? Makes sense to simplify this and always return the same type.

**Comment by tetienne** [comment]
I don’t see cases where it would break stuff. Most of the time you want a specific state so you test your list. But mypy will still complain in some cases as we still declare the variables as optional and setting an empty array as default parameter is not a good practice :S

**Comment by iMicknl** [comment]
> But mypy will still complain in some cases as we still declare the variables as optional and setting an empty array as default parameter is not a good practice :S

Hmm, does this mean that we can't merge this one yet? Or is this PR ready to merge :-)

**Comment by tetienne** [comment]
Well that's OK for now.

**Review by iMicknl — APPROVED** [review]

**Pull request merged**
