### PR TITLE
Make widget name optional

### PR DESCRIPTION
**Pull request by iMicknl**
Fixes https://github.com/iMicknl/ha-tahoma/issues/205

@tetienne would be good to use the definitions below for the unit tests at some point. The top one with `available: false` has indeed issues

Do you know a way to not break the component, if we miss some required strings? 

```
    {
      "creationTime": 1472213846000,
      "lastUpdateTime": 1472213846000,
      "label": "ZWAVE (2#1)",
      "deviceURL": "zwave://xxxx-xxxx-xxxx/2#1",
      "shortcut": false,
      "controllableName": "zwave:ZWaveOccupancySensor",
      "definition": {
        "commands": [],
        "states": [],
        "dataProperties": [],
        "qualifiedName": "zwave:ZWaveOccupancySensor",
        "type": "UNKNOWN"
      },
      "available": false,
      "enabled": true,
      "placeOID": "xxx",
      "type": 0,
      "oid": "xxx-xxx-xxx-xxx-xxx"
    },
    {
      "creationTime": 1472213846000,
      "lastUpdateTime": 1472213846000,
      "label": "ZWAVE (2#2)",
      "deviceURL": "zwave://xxxx-xxxx-xxxx/2#2",
      "shortcut": false,
      "controllableName": "zwave:ZWaveTemperatureSensor",
      "definition": {
        "commands": [
          {
            "commandName": "refreshTemperature",
            "nparams": 0
          }
        ],
        "states": [
          {
            "values": [
              "failed"
            ],
            "type": "DiscreteState",
            "qualifiedName": "core:DeviceDefectState"
          },
          {
            "type": "DataState",
            "qualifiedName": "core:NeighboursAddressesState"
          },
          {
            "type": "ContinuousState",
            "qualifiedName": "core:TemperatureState"
          }
        ],
        "dataProperties": [],
        "widgetName": "TemperatureSensor",
        "uiClass": "TemperatureSensor",
        "qualifiedName": "zwave:ZWaveTemperatureSensor",
        "type": "SENSOR"
      },
      "attributes": [
        {
          "name": "core:MeasuredValueType",
          "type": 3,
          "value": "core:TemperatureInCelcius"
        }
      ],
      "available": false,
      "enabled": true,
      "placeOID": "xxx",
      "widget": "TemperatureSensor",
      "type": 2,
      "oid": "xxx-xxx-xxx-xxx-xxx",
      "uiClass": "TemperatureSensor"
    },
    {
      "creationTime": 1472213846000,
      "lastUpdateTime": 1472213846000,
      "label": "ZWAVE (2#3)",
      "deviceURL": "zwave://xxxx-xxxx-xxxx/2#3",
      "shortcut": false,
      "controllableName": "zwave:ZWaveLightSensor",
      "definition": {
        "commands": [],
        "states": [
          {
            "values": [
              "failed"
            ],
            "type": "DiscreteState",
            "qualifiedName": "core:DeviceDefectState"
          },
          {
            "type": "ContinuousState",
            "qualifiedName": "core:LuminanceState"
          },
          {
            "type": "DataState",
            "qualifiedName": "core:NeighboursAddressesState"
          }
        ],
        "dataProperties": [],
        "widgetName": "LuminanceSensor",
        "uiClass": "LightSensor",
        "qualifiedName": "zwave:ZWaveLightSensor",
        "type": "SENSOR"
      },
      "attributes": [
        {
          "name": "core:MeasuredValueType",
          "type": 3,
          "value": "core:LuminanceInLux"
        }
      ],
      "available": false,
      "enabled": true,
      "placeOID": "xxx",
      "widget": "LuminanceSensor",
      "type": 2,
      "oid": "xxx-xxx-xxx-xxx-xxx",
      "uiClass": "LightSensor"
    }
```

### CODE REVIEW

**Comment by tetienne** [comment]
@iMicknl We have to do for all the parameters what you did for the widget name in this PR: make them optional. Or only take **kwargs as parameter.

**Comment by tetienne** [comment]
As you know now how mock async http request, it would be nice to add a unit test using the setup of this PR, like this: https://github.com/tetienne/somfy-open-api/blob/master/tests/test_somfy_api.py#L19

**Comment by iMicknl** [comment]
@tetienne can we merge this one first? I am fine by adding tests at some point, however would be great to add this quickly to unblock someone of using the new integration.

**Comment by tetienne** [comment]
Are we sure this time we won't miss any fields? If yes I'm good.

**Pull request merged**
