### PR TITLE
Add a list of supported Overkiz servers as constant

### PR DESCRIPTION
**Pull request by iMicknl**

### CODE REVIEW

**Review by tetienne — COMMENTED** [review]
You cannot use an enum ?

**Comment by iMicknl** [comment]
> You cannot use an enum ?

That was quick! I don't think you can use an ENUM with multiple values? And I didn't like the approach of ha-tahoma a lot, where we have multiple lists that share the same key. (endpoint + manufacturer)

**Comment by tetienne** [comment]
Ah yes indeed. Sorry for enum I still think about Java where they are very powerful.

**Review by tetienne — APPROVED** [review]

**Comment by iMicknl** [comment]
> Ah yes indeed. Sorry for enum I still think about Java where they are very powerful.

Makes sense, in Python you would need an external package to simulate the same.

However, I will just try to see if I can get it working in HA config flow before I merge this one. It seems that it is not possible to work with key/value pairs in the config flow dropdown.

```python
        vol.Required(CONF_HUB, default=self._default_hub): vol.In(
                        SUPPORTED_HUBS.keys()
                    ),
```

**Comment by iMicknl** [comment]
It makes more sense to have them as NamedTuple, instead of dataclass. See https://github.com/home-assistant/core/pull/53341/files.

**Pull request merged**
